logger:
    directory: /home/vincent/logs/modularity
    level: DEBUG
    traceRequest: true
    
opensilex-core:
    basePath: /opensilex-phis

opensilex-core-rdf4j:
    repository: diaphen
    
opensilex-core-mongo:
    database: diaphen

phis-ws-pg:
    database: diaphen
    username: phis
    password: azerty
    
## Legacy service
phis-ws-service:
    infrastructure: diaphen
    
    uploadFileServerUsername: vincent
    uploadFileServerPassword: pic3.14
    uploadFileServerDirectory: /home/phis2ws/documents/instance
    
    layerFileServerDirectory: /var/www/html/layers
    layerFileServerAddress: http://localhost/layers
    
    uploadImageServerDirectory: /var/www/html/images
    imageFileServerDirectory: http://localhost/images
    
    webAppApiDocsName: opensilex-phis